### ISSUE TITLE
Uploaded art assets won't show up in app

### ISSUE THREAD

**Issue by PanyBavl** [Dekita/Discord-RPC-Tool#3]
Any art assets I've uploaded won't show up in the app
![image](https://user-images.githubusercontent.com/70045376/162591511-2b6dd032-e518-43ca-ad6e-811caeff7d21.png)
![image](https://user-images.githubusercontent.com/70045376/162591516-02881eee-0712-44b7-93c0-6957e4b35c8a.png)

I tried even naming the assets what it says in the apps box, but that didn't work either.

**Comment by Dekita** [comment]
oh, the app images only refresh when activities are changed, and on app load. If you change your app id, and change it back, they should refresh. if they still arent showing. refresh the discord developer portal to make sure the images properly saved. because of how they cache images, it can sometimes takes a while for them to show, and sometimes they dont upload properly at all. 

Let me know if that is any help to you

**Comment by Dekita** [comment]
Closing issue as no response and recent updates should help clear up the process of adding images.
